### ISSUE TITLE
1.16.5

### ISSUE THREAD

**Issue by vaniron** [EverNife/FinalConsoleFilter#1]
Any chance of 1.16.5 for hybrids (Arclight) ?

**Comment by speccycy** [comment]
i tested
FinalConsoleFilter Can run on Arclight 1.16.5

**Comment by EverNife** [comment]
Nothing hás changed on the logging API between ALL Minecraft versions.

 It should work fine, if does not work for a specific forge log let me know I Will try to fix it.
